from typing import Any, ClassVar, List, Optional, Tuple, Union, overload, Literal
from sage.structure.element import FieldElement, Element
from sage.categories.morphism import Morphism
from sage.rings.integer import Integer
from sage.rings.rational_field import RationalField as RationalField_class
import gmpy2

# We use Any for base classes that might not be stubbed yet to avoid errors
RealDoubleFieldABC = Any

class RealDoubleField_class(RealDoubleFieldABC):
    _element_constructor_: ClassVar[type]
    prec: int
    nan: RealDoubleElement

    def __init__(self) -> None: ...
    def is_exact(self) -> bool: ...
    def _latex_(self) -> str: ...
    def _sage_input_(self, sib: Any, coerced: Any) -> Any: ...
    def __repr__(self) -> str: ...
    def _repr_option(self, key: str) -> Any: ...
    def __richcmp__(self, x: Any, op: Any) -> Any: ...
    def construction(self) -> Tuple[Any, Any]: ...
    def complex_field(self) -> Any: ...  # Returns ComplexDoubleField
    def algebraic_closure(self) -> Any: ... # Returns ComplexDoubleField
    def _coerce_map_from_(self, S: Any) -> Optional[Morphism]: ...
    def _magma_init_(self, magma: Any) -> str: ...
    def _fricas_init_(self) -> str: ...
    def _polymake_init_(self) -> str: ...
    def precision(self) -> int: ...
    def to_prec(self, prec: int) -> Any: ...
    def gen(self, n: int = 0) -> RealDoubleElement: ...
    def ngens(self) -> int: ...
    def characteristic(self) -> Integer: ...
    def random_element(self, min: float = -1, max: float = 1) -> RealDoubleElement: ...
    def name(self) -> str: ...
    def __hash__(self) -> int: ...
    def pi(self) -> RealDoubleElement: ...
    def euler_constant(self) -> RealDoubleElement: ...
    def log2(self) -> RealDoubleElement: ...
    def factorial(self, n: int) -> RealDoubleElement: ...
    def zeta(self, n: int = 2) -> RealDoubleElement: ...
    def NaN(self) -> RealDoubleElement: ...
    def _factor_univariate_polynomial(self, f: Any) -> Any: ...

class RealDoubleElement(FieldElement):
    __array_interface__: ClassVar[dict]
    ceiling: ClassVar[Any]
    nan: ClassVar[Any]
    algdep: ClassVar[Any]

    def __init__(self, x: Any) -> None: ...
    def _magma_init_(self, magma: Any) -> str: ...
    def __reduce__(self) -> Tuple[Any, Tuple[Any]]: ...
    def prec(self) -> int: ...
    def ulp(self) -> RealDoubleElement: ...
    def real(self) -> RealDoubleElement: ...
    def imag(self) -> RealDoubleElement: ...
    def __complex__(self) -> complex: ...
    def _integer_(self, ZZ: Optional[Any] = None) -> Integer: ...
    def __mpfr__(self) -> gmpy2.mpfr: ...
    def _interface_init_(self, I: Optional[Any] = None) -> str: ...
    def _mathematica_init_(self) -> str: ...
    def _sage_input_(self, sib: Any, coerced: Any) -> Any: ...
    def _repr_(self) -> str: ...
    def __format__(self, format_spec: str) -> str: ...
    def _latex_(self) -> str: ...
    def __hash__(self) -> int: ...
    def _im_gens_(self, codomain: Any, im_gens: Any, base_map: Optional[Any] = None) -> Element: ...
    def str(self) -> str: ...
    def __copy__(self) -> RealDoubleElement: ...
    def __deepcopy__(self, memo: Any) -> RealDoubleElement: ...
    def integer_part(self) -> Integer: ...
    def sign_mantissa_exponent(self) -> Tuple[int, int, int]: ...
    def as_integer_ratio(self) -> Tuple[Integer, Integer]: ...
    def __invert__(self) -> RealDoubleElement: ...
    def _add_(self, right: Any) -> RealDoubleElement: ...
    def _sub_(self, right: Any) -> RealDoubleElement: ...
    def _mul_(self, right: Any) -> RealDoubleElement: ...
    def _div_(self, right: Any) -> RealDoubleElement: ...
    def __neg__(self) -> RealDoubleElement: ...
    def conjugate(self) -> RealDoubleElement: ...
    def __abs__(self) -> RealDoubleElement: ...
    def abs(self) -> RealDoubleElement: ...
    def __lshift__(self, y: Any) -> Any: ...
    def __rshift__(self, y: Any) -> Any: ...
    def multiplicative_order(self) -> Union[int, Any]: ... # Returns int or infinity
    def sign(self) -> int: ...
    def round(self) -> Integer: ...
    def floor(self) -> Integer: ...
    def ceil(self) -> Integer: ...
    def trunc(self) -> Integer: ...
    def frac(self) -> RealDoubleElement: ...
    def __float__(self) -> float: ...
    def _rpy_(self) -> float: ...
    def __int__(self) -> int: ...
    def _complex_mpfr_field_(self, CC: Any) -> Element: ...
    def _complex_double_(self, CDF: Any) -> Element: ...
    def __pari__(self) -> Any: ...
    def is_NaN(self) -> bool: ...
    def is_positive_infinity(self) -> bool: ...
    def is_negative_infinity(self) -> bool: ...
    def is_infinity(self) -> bool: ...
    def NaN(self) -> RealDoubleElement: ...
    @overload
    def sqrt(self, extend: bool = ..., all: Literal[False] = ...) -> Union[RealDoubleElement, Any]: ...
    @overload
    def sqrt(self, extend: bool = ..., all: Literal[True] = ...) -> List[Union[RealDoubleElement, Any]]: ...
    def is_square(self) -> bool: ...
    def is_integer(self) -> bool: ...
    def cube_root(self) -> RealDoubleElement: ...
    def agm(self, other: Any) -> RealDoubleElement: ...
    def algebraic_dependency(self, n: int) -> Any: ...

class ToRDF(Morphism):
    def __init__(self, R: Any) -> None: ...
    def _call_(self, x: Any) -> RealDoubleElement: ...
    def _repr_type(self) -> str: ...

RDF: RealDoubleField_class
_RDF: RealDoubleField_class

def RealDoubleField() -> RealDoubleField_class: ...
def is_RealDoubleElement(x: Any) -> bool: ...
