from typing import Any, Optional, Union
from sage.structure.parent import Parent
from sage.categories.category import Category

class Group(Parent):
    def __init__(self, base: Any = None, category: Optional[Union[Category, tuple]] = None) -> None: ...
    def is_abelian(self) -> bool: ...
    def is_commutative(self) -> bool: ...
    def order(self) -> Any: ...  # Returns Integer or Infinity
    def is_finite(self) -> bool: ...
    def is_trivial(self) -> bool: ...
    def is_multiplicative(self) -> bool: ...
    def _an_element_(self) -> Any: ...
    def quotient(self, H: Any, **kwds: Any) -> Any: ...

class AbelianGroup(Group):
    def is_abelian(self) -> bool: ...

class FiniteGroup(Group):
    def __init__(self, base: Any = None, category: Optional[Union[Category, tuple]] = None) -> None: ...
    def is_finite(self) -> bool: ...

class AlgebraicGroup(Group): ...

def is_Group(x: Any) -> bool: ...
