from typing import Any
from sage.structure.sage_object import SageObject

macro_regex: Any

class HtmlFragment(str, SageObject): ...

def math_parse(s: str) -> HtmlFragment: ...

class MathJaxExpr:
    def __init__(self, y: str) -> None: ...
    def __repr__(self) -> str: ...
    def __add__(self, y: str) -> MathJaxExpr: ...
    def __radd__(self, y: str) -> MathJaxExpr: ...

class MathJax:
    def __call__(self, x: Any, combine_all: bool = False) -> MathJaxExpr: ...
    def eval(self, x: Any, globals: dict[str, Any] | None = None, locals: dict[str, Any] | None = None, mode: str = 'display', combine_all: bool = False) -> MathJaxExpr: ...

class HTMLFragmentFactory(SageObject):
    def _repr_(self) -> str: ...
    def __call__(self, obj: Any, concatenate: bool = True, strict: bool = False) -> HtmlFragment: ...
    def eval(self, s: str, locals: dict[str, Any] | None = None) -> HtmlFragment: ...
    def iframe(self, url: str, height: int = 400, width: int = 800) -> HtmlFragment: ...

html: HTMLFragmentFactory

def pretty_print_default(enable: bool = True) -> None: ...
