from typing import Any, Iterator, overload

def xsrange(start: Any, end: Any = None, step: Any = 1, universe: Any = None, *, coerce: bool = True, include_endpoint: bool = False, endpoint_tolerance: float = 1e-5) -> Iterator[Any]: ...
def srange(*args: Any, **kwds: Any) -> list[Any]: ...
def ellipsis_iter(*args: Any, step: Any = None) -> Iterator[Any]: ...
def ellipsis_range(*args: Any, step: Any = None) -> list[Any]: ...
